Linux|bmfazio-pc|x86_64|bmfazio: /home/bmfazio/Documents/datasets
Windows|>= 8 x64|build 9200|DESKTOP-5CGB5S0|x86-64|Personal|Personal|Personal: D:/datasets
Windows|>= 8 x64|build 9200|DESKTOP-U6PGH7C|x86-64|Asus-N56|Asus-N56|Asus-N56: D:/datasets
